#!/bin/bash

./xmlchange --force CLM_BLDNML_OPTS="-fire_emis" --append
./xmlchange --force BFBFLAG="TRUE"

./xmlchange --force DATM_CPLHIST_CASE=b.e20.B1850.f09_g17.pi_control.all.221.cplhist
./xmlchange --force DATM_CPLHIST_DIR=/glade/p/cesm/bgcwg_dev/forcing/b.e20.B1850.f09_g17.pi_control.all.221.cplhist/cpl/hist.mon
./xmlchange --force DATM_CPLHIST_YR_ALIGN=1
./xmlchange --force DATM_CPLHIST_YR_END=84
./xmlchange --force DATM_CPLHIST_YR_START=82
